version: '3.7'

services:
  hospital-triage-db:
    image: postgres
    volumes:
        # - data:/var/lib/postgresql/data:rw
        - ./scripts/db:/docker-entrypoint-initdb.d:rw
  hospital-triage:
    container_name: triage
    env_file:
      - ./etc/env/apps.env
    build: .
    command: bash -c "chmod +x scripts/run/dev.sh && ./scripts/run/dev.sh"
    environment:
      - DB_NAME=myproject
      - DB_USER=myprojectuser
      - DB_PASSWORD=password
      - DB_HOST=hospital-triage-db
      - DB_PORT=5432
      - PROD=0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - hospital-triage-db
